### ISSUE TITLE
mycloset page : 정렬 이슈

### ISSUE THREAD

**Issue by baaaam771** [ProjectFFF/FFF#8]
사용자 프로필 정렬이 안됨
![프로필](https://user-images.githubusercontent.com/60038592/92518705-b91b4180-f253-11ea-8a76-5c48cce56965.PNG)
`<style type="text/css">
  .account_container {
    padding: 100px;
    text-align: center;
    vertical-align: middle;
  }
</style>`

**Comment by KimHoya** [comment]
html에서 css사용 안하고 가운데 정렬하려면 center 태그 사용해야 한다고 하는데
내가 몇군에 center 태그 넣어보니까 정렬이 안되네...
내가 잘 못넣어서 그럴도 있으니까 저거 고민 안해봤으면 한 번 시도해보는데 좋을꺼 같어!

**Comment by Dohyeong-Cheon** [comment]
div class="col-lg-4"를  div class="col-lg-12"로 변경하면 중앙 정렬 돼!!

http://blog.naver.com/PostView.nhn?blogId=dkdlfhd&logNo=220484063026&categoryNo=43&parentCategoryNo=0&viewDate=&currentPage=1&postListTopCurrentPage=1&from=postView
부트스트랩 그리드 설명

**Comment by baaaam771** [comment]
https://getbootstrap.com/docs/4.5/layout/grid/
그리드 부트스트탭 원문

**Comment by baaaam771** [comment]
정렬 해결
![옷장](https://user-images.githubusercontent.com/60038592/92937682-9f157500-f486-11ea-8703-ec92eb7b90c4.PNG)
이슈 종료해도 될것 같습니다
